$fp = "c:\Dev\Application Site\JobPortal\Controllers\AdminController.cs"
$enc = [System.Text.Encoding]::Unicode
$c = [System.IO.File]::ReadAllText($fp, $enc)
$lines = [System.Collections.Generic.List[string]]($c -split "`r`n")
Write-Host "Before: $($lines.Count) lines"

# Remove lines 133 through 208 (the body of Create POST, excluding the closing })
# Line 133 is "{", line 208 is "return RedirectToAction(nameof(Index));"
# We keep lines 129-132 (decorators + signature) and 209+ (else branch + closing)
$removeStart = 133
$removeEnd = 208
$removeCount = $removeEnd - $removeStart + 1
$lines.RemoveRange($removeStart, $removeCount)
Write-Host "Removed $removeCount lines starting at $removeStart"

$newBody = [string[]]@(
    '    {'
    '        Console.WriteLine("=== CREATE JOB START ===");'
    ''
    '        if (!ModelState.IsValid)'
    '        {'
    '            Console.WriteLine("=== MODELSTATE INVALID ===");'
    ''
    '            foreach (var entry in ModelState)'
    '            {'
    '                foreach (var error in entry.Value.Errors)'
    '                {'
    '                    Console.WriteLine($"Field: {entry.Key}, Error: {error.ErrorMessage}");'
    '                }'
    '            }'
    '        }'
    ''
    '        if (ModelState.IsValid)'
    '        {'
    '            Console.WriteLine("ModelState is valid");'
    '            Console.WriteLine($"Title: {model.Title}");'
    '            Console.WriteLine($"OwnerUserId: {model.OwnerUserId}");'
    '            Console.WriteLine($"Reviewer count: {model.ReviewerUserIds?.Count}");'
    ''
    '            if (model.ScorecardTemplateId.HasValue)'
    '            {'
    '                var template = await _scorecardTemplateService.GetTemplateById(model.ScorecardTemplateId.Value);'
    '                if (template == null)'
    '                {'
    '                    ModelState.AddModelError("ScorecardTemplateId", "The selected scorecard template does not exist.");'
    '                    await PopulateScorecardTemplateOptions(model.ScorecardTemplateId);'
    '                    await PopulateOwnerAndReviewerOptions();'
    '                    return View(model);'
    '                }'
    '            }'
    ''
    '            // Validate owner'
    '            if (!string.IsNullOrEmpty(model.OwnerUserId))'
    '            {'
    '                var ownerUser = await _context.Users.FindAsync(model.OwnerUserId);'
    '                if (ownerUser == null)'
    '                {'
    '                    ModelState.AddModelError("OwnerUserId", "Selected owner does not exist.");'
    '                    await PopulateScorecardTemplateOptions(model.ScorecardTemplateId);'
    '                    await PopulateOwnerAndReviewerOptions();'
    '                    return View(model);'
    '                }'
    '            }'
    ''
    '            try'
    '            {'
    '                Console.WriteLine("Creating job...");'
    ''
    '                var job = new Job'
    '                {'
    '                    Title = model.Title,'
    '                    Description = model.Description,'
    '                    ScorecardTemplateId = model.ScorecardTemplateId,'
    '                    OwnerUserId = string.IsNullOrEmpty(model.OwnerUserId) ? null : model.OwnerUserId'
    '                };'
    ''
    '                await _jobCommandService.CreateJobAsync(job);'
    '                Console.WriteLine($"Job created successfully with Id={job.Id}");'
    ''
    '                // Assign reviewers'
    '                if (model.ReviewerUserIds != null && model.ReviewerUserIds.Any())'
    '                {'
    '                    Console.WriteLine($"Assigning {model.ReviewerUserIds.Count} reviewers...");'
    '                    foreach (var userId in model.ReviewerUserIds)'
    '                    {'
    '                        var user = await _context.Users.FindAsync(userId);'
    '                        if (user != null)'
    '                        {'
    '                            var roles = await _context.UserRoles'
    '                                .Where(ur => ur.UserId == userId)'
    '                                .Join(_context.Roles, ur => ur.RoleId, r => r.Id, (ur, r) => r.Name)'
    '                                .ToListAsync();'
    '                            if (roles.Any(r => r == "Admin" || r == "Recruiter"))'
    '                            {'
    '                                _context.Set<JobUser>().Add(new JobUser'
    '                                {'
    '                                    JobId = job.Id,'
    '                                    UserId = userId,'
    '                                    Role = "Reviewer",'
    '                                    IsActive = true'
    '                                });'
    '                            }'
    '                        }'
    '                    }'
    '                    await _context.SaveChangesAsync();'
    '                    Console.WriteLine("Reviewers assigned");'
    '                }'
    '            }'
    '            catch (Exception ex)'
    '            {'
    '                Console.WriteLine("=== ERROR DURING JOB CREATION ===");'
    '                Console.WriteLine(ex.Message);'
    '                Console.WriteLine(ex.StackTrace);'
    '                ModelState.AddModelError("", "An error occurred while creating the job.");'
    '                await PopulateScorecardTemplateOptions(model.ScorecardTemplateId);'
    '                await PopulateOwnerAndReviewerOptions();'
    '                return View(model);'
    '            }'
    ''
    '            Console.WriteLine("Redirecting to Index");'
    '            return RedirectToAction(nameof(Index));'
    '        }'
)

$lines.InsertRange($removeStart, $newBody)
$result = $lines -join "`r`n"
[System.IO.File]::WriteAllText($fp, $result, $enc)
Write-Host "After: $($lines.Count) lines"
Write-Host "Done!"
